
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from './materials/material'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="w-screen h-screen flex items-center content-center">
            <div className='w-screen h-screen xl:w-[1400px] mx-auto'>
          {children}
          </div>
          </div></body>
      </html>
    </ThemeProvider>
  )
}
